#!/bin/sh
#
# Copyright (c) 2015 Google, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

JAR_FILE=`which "$0" 2>/dev/null`

if [[ -n "$JAVA_HOME" ]]; then
  JAVA_CMD="$JAVA_HOME/bin/java"
  if [[ ! -f $JAVA_CMD ]]; then
    echo "Cannot find java binary at $JAVA_CMD"
    exit 1
  fi
else
  if [[ ! `which java` ]]; then
    echo "Cannot find java binary on the executable PATH"
    exit 1
  fi
  JAVA_CMD=`which java`
fi

if [[ ! -x $JAVA_CMD ]]; then
  echo "Java command is not executable: $JAVA_CMD"
  exit 1
fi

"$JAVA_CMD" $JVM_ARGS -jar $0 "$@"
exit 1 
